In [6]:
import os
import numpy as np, pandas as pd
import matplotlib.pyplot as plt
from sklearn import  metrics, model_selection
# from sklearn.ensemble import XGBClassifier
from xgboost import XGBClassifier

In [11]:
data = pd.read_csv('car.data',names=['buying','maint','doors','persons','lug_boot','safety','class'])

In [17]:
data

     buying  maint  doors persons lug_boot safety  class
0     vhigh  vhigh      2       2    small    low      0
1     vhigh  vhigh      2       2    small    med      0
2     vhigh  vhigh      2       2    small   high      0
3     vhigh  vhigh      2       2      med    low      0
4     vhigh  vhigh      2       2      med    med      0
5     vhigh  vhigh      2       2      med   high      0
6     vhigh  vhigh      2       2      big    low      0
7     vhigh  vhigh      2       2      big    med      0
8     vhigh  vhigh      2       2      big   high      0
9     vhigh  vhigh      2       4    small    low      0
10    vhigh  vhigh      2       4    small    med      0
11    vhigh  vhigh      2       4    small   high      0
12    vhigh  vhigh      2       4      med    low      0
13    vhigh  vhigh      2       4      med    med      0
14    vhigh  vhigh      2       4      med   high      0
15    vhigh  vhigh      2       4      big    low      0
16    vhigh  vhigh      2       4      big    med      0
17    vhigh  vhigh      2       4      big   high      0
18    vhigh  vhigh      2    more    small    low      0
19    vhigh  vhigh      2    more    small    med      0
20    vhigh  vhigh      2    more    small   high      0
21    vhigh  vhigh      2    more      med    low      0
22    vhigh  vhigh      2    more      med    med      0
23    vhigh  vhigh      2    more      med   high      0
24    vhigh  vhigh      2    more      big    low      0
25    vhigh  vhigh      2    more      big    med      0
26    vhigh  vhigh      2    more      big   high      0
27    vhigh  vhigh      3       2    small    low      0
28    vhigh  vhigh      3       2    small    med      0
29    vhigh  vhigh      3       2    small   high      0
...     ...    ...    ...     ...      ...    ...    ...
1698    low    low      4    more      big    low      0
1699    low    low      4    more      big    med      3
1700    low    low      4    more      big   high      2
1701    low    low  5more       2    small    low      0
1702    low    low  5more       2    small    med      0
1703    low    low  5more       2    small   high      0
1704    low    low  5more       2      med    low      0
1705    low    low  5more       2      med    med      0
1706    low    low  5more       2      med   high      0
1707    low    low  5more       2      big    low      0
1708    low    low  5more       2      big    med      0
1709    low    low  5more       2      big   high      0
1710    low    low  5more       4    small    low      0
1711    low    low  5more       4    small    med      1
1712    low    low  5more       4    small   high      3
1713    low    low  5more       4      med    low      0
1714    low    low  5more       4      med    med      3
1715    low    low  5more       4      med   high      2
1716    low    low  5more       4      big    low      0
1717    low    low  5more       4      big    med      3
1718    low    low  5more       4      big   high      2
1719    low    low  5more    more    small    low      0
1720    low    low  5more    more    small    med      1
1721    low    low  5more    more    small   high      3
1722    low    low  5more    more      med    low      0
1723    low    low  5more    more      med    med      3
1724    low    low  5more    more      med   high      2
1725    low    low  5more    more      big    low      0
1726    low    low  5more    more      big    med      3
1727    low    low  5more    more      big   high      2

[1728 rows x 7 columns]

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
buying      1728 non-null object
maint       1728 non-null object
doors       1728 non-null object
persons     1728 non-null object
lug_boot    1728 non-null object
safety      1728 non-null object
class       1728 non-null object
dtypes: object(7)
memory usage: 94.6+ KB

In [14]:
data['class'],class_names = pd.factorize(data['class'])

In [15]:
data['class']

0       0
1       0
2       0
3       0
4       0
5       0
6       0
7       0
8       0
9       0
10      0
11      0
12      0
13      0
14      0
15      0
16      0
17      0
18      0
19      0
20      0
21      0
22      0
23      0
24      0
25      0
26      0
27      0
28      0
29      0
       ..
1698    0
1699    3
1700    2
1701    0
1702    0
1703    0
1704    0
1705    0
1706    0
1707    0
1708    0
1709    0
1710    0
1711    1
1712    3
1713    0
1714    3
1715    2
1716    0
1717    3
1718    2
1719    0
1720    1
1721    3
1722    0
1723    3
1724    2
1725    0
1726    3
1727    2
Name: class, Length: 1728, dtype: int64

In [19]:
print(class_names)
print(data['class'].unique())

Index(['unacc', 'acc', 'vgood', 'good'], dtype='object')
[0 1 2 3]

In [20]:
data['buying'],_ = pd.factorize(data['buying'])
data['maint'],_ = pd.factorize(data['maint'])
data['doors'],_ = pd.factorize(data['doors'])
data['persons'],_ = pd.factorize(data['persons'])
data['lug_boot'],_ = pd.factorize(data['lug_boot'])
data['safety'],_ = pd.factorize(data['safety'])

In [21]:
data.head()

   buying  maint  doors  persons  lug_boot  safety  class
0       0      0      0        0         0       0      0
1       0      0      0        0         0       1      0
2       0      0      0        0         0       2      0
3       0      0      0        0         1       0      0
4       0      0      0        0         1       1      0

In [22]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
buying      1728 non-null int64
maint       1728 non-null int64
doors       1728 non-null int64
persons     1728 non-null int64
lug_boot    1728 non-null int64
safety      1728 non-null int64
class       1728 non-null int64
dtypes: int64(7)
memory usage: 94.6 KB

In [23]:
X = data.iloc[:,:-1]
y = data.iloc[:,-1]

In [28]:
# split data randomly into 70% training and 30% test
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=0.3, random_state=123)

In [37]:
model = XGBClassifier(objective='binary:logistic',max_depth=2,learning_rate=1,silent=1,n_estimators=5)
model.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, learning_rate=1,
              max_delta_step=0, max_depth=2, min_child_weight=1, missing=None,
              n_estimators=5, n_jobs=1, nthread=None,
              objective='multi:softprob', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=1, seed=None, silent=0,
              subsample=1, verbosity=1)

In [36]:
# ? XGBClassifier

In [38]:
# use the model to make predictions with the test data
y_pred = model.predict(X_test)
# how did our model perform?
count_misclassified = (y_test != y_pred).sum()
print('Misclassified samples: {}'.format(count_misclassified))
accuracy = metrics.accuracy_score(y_test, y_pred)
print('Accuracy: {:.2f}'.format(accuracy))

Misclassified samples: 58
Accuracy: 0.89